## ONE D ARRAY


In [ ]:
import numpy as np

In [2]:

arr1 = np.array([1,2,3,4,5,6])

In [3]:
print(arr1)

[1 2 3 4 5 6]


In [4]:
arr1

array([1, 2, 3, 4, 5, 6])

In [5]:
arr1[0]

np.int64(1)

In [6]:
np.type(arr1)

AttributeError: module 'numpy' has no attribute 'type'

In [7]:
type(arr1)

numpy.ndarray

In [8]:
arr1.ndim

1

In [9]:
arr1.size

6

In [10]:
arr1.dtype

dtype('int64')

In [11]:
arr1.shape

(6,)

In [12]:
arr2 = np.array([[1,2,3],[4,5,6]])

In [13]:
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [14]:
arr2[0]

array([1, 2, 3])

In [15]:
arr2[0,2]

np.int64(3)

In [16]:
arr2.ndim

2

In [17]:
arr2.shape

(2, 3)

In [18]:
arr2.dtype

dtype('int64')

In [19]:
type(arr2)

numpy.ndarray

In [20]:
arr2.size

6

In [21]:
arr3 = np.array([[[1,2,3],[4,5,6]],[[11,12,13],[14,15,16]]])

In [22]:
arr3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[11, 12, 13],
        [14, 15, 16]]])

In [23]:
arr3.ndmin

AttributeError: 'numpy.ndarray' object has no attribute 'ndmin'

In [24]:
arr3.ndim

3

In [25]:
arr3.shape

(2, 2, 3)

In [26]:
arr3.size

12

In [27]:
arr3.dtype

dtype('int64')

In [28]:
type(arr3)

numpy.ndarray

In [29]:
arr3[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [30]:
arr3[0][1]

array([4, 5, 6])

In [31]:
arr3[0][1][1]

np.int64(5)

In [32]:
arr3[0,1,2]

np.int64(6)

In [33]:
randomArr = np.random.rand(6)

In [34]:
randomArr

array([0.47326128, 0.04905802, 0.38091277, 0.53604573, 0.67523488,
       0.22144704])

In [35]:
randomArr2 = np.random.rand(3,4)

In [36]:
randomArr2

array([[0.46776561, 0.37597257, 0.78947749, 0.41508773],
       [0.08568376, 0.38396708, 0.59380329, 0.69719291],
       [0.68219786, 0.37024728, 0.13798024, 0.3476073 ]])

In [37]:
randomArr3 = np.random.rand(3,3,4)

In [38]:
randomArr3

array([[[0.20925157, 0.89162149, 0.25452667, 0.03506842],
        [0.50101412, 0.62569228, 0.16972821, 0.4512526 ],
        [0.52582966, 0.9119248 , 0.20187626, 0.15824466]],

       [[0.2152297 , 0.38337624, 0.44532367, 0.87629797],
        [0.55223218, 0.19274801, 0.84304517, 0.59196484],
        [0.02791457, 0.85131902, 0.47550376, 0.90893461]],

       [[0.67948155, 0.25887369, 0.05653358, 0.09980139],
        [0.6284593 , 0.04660604, 0.47514634, 0.76339985],
        [0.13148538, 0.42693856, 0.27784123, 0.26315301]]])

In [39]:
zeros = np.zeros(3,2,3)

TypeError: Cannot interpret '2' as a data type

In [40]:
zeros = np.zeros([3,2,3])

In [41]:
zeros

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [42]:
oneArr = np.ones([2,3])

In [43]:
oneArr

array([[1., 1., 1.],
       [1., 1., 1.]])

In [45]:
zeros

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [46]:
zeros[1]

array([[0., 0., 0.],
       [0., 0., 0.]])

In [47]:
full = np.full([3,2,3],9)

In [48]:
full

array([[[9, 9, 9],
        [9, 9, 9]],

       [[9, 9, 9],
        [9, 9, 9]],

       [[9, 9, 9],
        [9, 9, 9]]])

In [49]:
full = np.full([3,2,3],9+1)

In [50]:
full


array([[[10, 10, 10],
        [10, 10, 10]],

       [[10, 10, 10],
        [10, 10, 10]],

       [[10, 10, 10],
        [10, 10, 10]]])

In [51]:
arr3[-1]

array([[11, 12, 13],
       [14, 15, 16]])

In [52]:
arr3[-1][0][2]

np.int64(13)

In [53]:
a1 = np.array([[[1,2,3],[4,5,6]],[[11,12,13],[14,15,16]]])
a2 = np.array([[[21,22,23],[34,35,36]],[[111,112,113],[214,215,216]]])

In [54]:
a1
a2

array([[[ 21,  22,  23],
        [ 34,  35,  36]],

       [[111, 112, 113],
        [214, 215, 216]]])

In [55]:
a1

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[11, 12, 13],
        [14, 15, 16]]])

In [56]:
np.add(a1,a2)

array([[[ 22,  24,  26],
        [ 38,  40,  42]],

       [[122, 124, 126],
        [228, 230, 232]]])

In [57]:
np.substract(a1,a2)

AttributeError: module 'numpy' has no attribute 'substract'

In [58]:
np.subtract(a1,a2)

array([[[ -20,  -20,  -20],
        [ -30,  -30,  -30]],

       [[-100, -100, -100],
        [-200, -200, -200]]])

In [59]:
np.subtract(a2,a1)

array([[[ 20,  20,  20],
        [ 30,  30,  30]],

       [[100, 100, 100],
        [200, 200, 200]]])

In [60]:
np.multiply(a1,a2)

array([[[  21,   44,   69],
        [ 136,  175,  216]],

       [[1221, 1344, 1469],
        [2996, 3225, 3456]]])

In [61]:
np.divide(a1,a2)

array([[[0.04761905, 0.09090909, 0.13043478],
        [0.11764706, 0.14285714, 0.16666667]],

       [[0.0990991 , 0.10714286, 0.11504425],
        [0.06542056, 0.06976744, 0.07407407]]])

In [62]:
arr3.sort

<function ndarray.sort(axis=-1, kind=None, order=None, *, stable=None)>

In [63]:
arr3.sort()

In [64]:
arr3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[11, 12, 13],
        [14, 15, 16]]])

In [65]:
arr3.shape

(2, 2, 3)

In [66]:
reshape = arr3.reshape((2,3,3))

ValueError: cannot reshape array of size 12 into shape (2,3,3)

In [67]:
a1 = np.array([[[1,2,3],[4,5,6]],[[11,12,13],[14,15,16]],[[21,22,23],[24,25,26]]])

In [68]:
a1.shape

(3, 2, 3)

In [69]:
alternate = a1.reshape((3,2,3))  

In [70]:
alternate

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[11, 12, 13],
        [14, 15, 16]],

       [[21, 22, 23],
        [24, 25, 26]]])

In [71]:
alternate = a1.reshape((2,3,3))  

In [72]:
alternate

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [11, 12, 13]],

       [[14, 15, 16],
        [21, 22, 23],
        [24, 25, 26]]])

In [73]:
np.sqrt(25)

np.float64(5.0)

In [74]:
mins =np.min(a1)

In [75]:
mins

np.int64(1)

In [76]:
max = np.max(a1)
max

np.int64(26)

In [77]:
np.abs(-11)

np.int64(11)

In [78]:
np.power(3,3)

np.int64(27)

In [79]:
a1[0,2,1]

IndexError: index 2 is out of bounds for axis 1 with size 2

In [80]:
a1

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[11, 12, 13],
        [14, 15, 16]],

       [[21, 22, 23],
        [24, 25, 26]]])

In [81]:
a1[0,1,1] = 500

In [82]:
a1


array([[[  1,   2,   3],
        [  4, 500,   6]],

       [[ 11,  12,  13],
        [ 14,  15,  16]],

       [[ 21,  22,  23],
        [ 24,  25,  26]]])

In [85]:
newArr = np.append((a1,a2))

TypeError: append() missing 1 required positional argument: 'values'

In [84]:
newArr

array([  1,   2,   3,   4, 500,   6,  11,  12,  13,  14,  15,  16,  21,
        22,  23,  24,  25,  26,  21,  22,  23,  34,  35,  36, 111, 112,
       113, 214, 215, 216])

In [86]:
a1

array([[[  1,   2,   3],
        [  4, 500,   6]],

       [[ 11,  12,  13],
        [ 14,  15,  16]],

       [[ 21,  22,  23],
        [ 24,  25,  26]]])

In [87]:
a2

array([[[ 21,  22,  23],
        [ 34,  35,  36]],

       [[111, 112, 113],
        [214, 215, 216]]])

In [88]:
newArr = np.append(a1,a2,axis=0)

In [89]:
newArr

array([[[  1,   2,   3],
        [  4, 500,   6]],

       [[ 11,  12,  13],
        [ 14,  15,  16]],

       [[ 21,  22,  23],
        [ 24,  25,  26]],

       [[ 21,  22,  23],
        [ 34,  35,  36]],

       [[111, 112, 113],
        [214, 215, 216]]])

In [90]:
newArr1n= np.append(a1,arr3,axis=1)

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 3 and the array at index 1 has size 2

In [91]:
arr3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[11, 12, 13],
        [14, 15, 16]]])

In [92]:
a1

array([[[  1,   2,   3],
        [  4, 500,   6]],

       [[ 11,  12,  13],
        [ 14,  15,  16]],

       [[ 21,  22,  23],
        [ 24,  25,  26]]])

In [93]:
a2

array([[[ 21,  22,  23],
        [ 34,  35,  36]],

       [[111, 112, 113],
        [214, 215, 216]]])

In [94]:
newArr = np.append(a2,arr3,axis=1)

In [95]:
newArr

array([[[ 21,  22,  23],
        [ 34,  35,  36],
        [  1,   2,   3],
        [  4,   5,   6]],

       [[111, 112, 113],
        [214, 215, 216],
        [ 11,  12,  13],
        [ 14,  15,  16]]])

In [96]:
newArr = np.append(a2,arr3,axis=0)

In [97]:
newArr

array([[[ 21,  22,  23],
        [ 34,  35,  36]],

       [[111, 112, 113],
        [214, 215, 216]],

       [[  1,   2,   3],
        [  4,   5,   6]],

       [[ 11,  12,  13],
        [ 14,  15,  16]]])

In [98]:
insertArr = np.insert(a2,1,arr3,axis=0)

In [99]:
insertArr

array([[[ 21,  22,  23],
        [ 34,  35,  36]],

       [[  1,   2,   3],
        [  4,   5,   6]],

       [[ 11,  12,  13],
        [ 14,  15,  16]],

       [[111, 112, 113],
        [214, 215, 216]]])

In [100]:
delete = np.delete(a2,0,axis=0)

In [101]:
delete

array([[[111, 112, 113],
        [214, 215, 216]]])

In [102]:
np.save('new_arr',arr3)

In [104]:
np.load('new_arr.npy')

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[11, 12, 13],
        [14, 15, 16]]])

In [106]:
a1 = np.array([[[1,2,3,4,5],[1,3,5,7,9],[2,4,6,8,10]]])

In [107]:
a1

array([[[ 1,  2,  3,  4,  5],
        [ 1,  3,  5,  7,  9],
        [ 2,  4,  6,  8, 10]]])

In [108]:
a1.max()

np.int64(10)

In [109]:
a1.sqrt()

AttributeError: 'numpy.ndarray' object has no attribute 'sqrt'

In [110]:
np.sqrt(a1)

array([[[1.        , 1.41421356, 1.73205081, 2.        , 2.23606798],
        [1.        , 1.73205081, 2.23606798, 2.64575131, 3.        ],
        [1.41421356, 2.        , 2.44948974, 2.82842712, 3.16227766]]])

In [112]:
np.multiply(a1,a1)

array([[[  1,   4,   9,  16,  25],
        [  1,   9,  25,  49,  81],
        [  4,  16,  36,  64, 100]]])